# Generated by Django 5.0.6 on 2024-07-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SERVER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverName', models.CharField(max_length=10, null=None, verbose_name='服务名称')),
                ('serverUrl', models.URLField(null=None, verbose_name='服务地址')),
                ('serverImg', models.ImageField(null=None, upload_to='serverImg/', verbose_name='服务图标')),
            ],
        ),
    ]
