# Generated by Django 5.0.6 on 2024-07-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=10, verbose_name='项目名称')),
                ('projectDetail', models.TextField(verbose_name='项目介绍')),
                ('projectImg', models.ImageField(upload_to='projectImg/', verbose_name='项目图片')),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='serverImg',
            field=models.ImageField(upload_to='serverImg/', verbose_name='服务图标'),
        ),
        migrations.AlterField(
            model_name='server',
            name='serverName',
            field=models.CharField(max_length=10, verbose_name='服务名称'),
        ),
        migrations.AlterField(
            model_name='server',
            name='serverUrl',
            field=models.URLField(verbose_name='服务地址'),
        ),
    ]
