# Generated by Django 5.0.6 on 2024-08-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_project_alter_server_serverimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectUrl',
            field=models.URLField(null=True, verbose_name='项目地址'),
        ),
    ]
