# Generated by Django 5.0.6 on 2024-09-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0004_remove_server_serverurl_server_serverurlfrp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
    ]
