# Generated by Django 5.0.6 on 2024-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0005_alter_project_options_alter_server_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectDetail',
            field=models.TextField(null=True, verbose_name='项目介绍'),
        ),
        migrations.AlterField(
            model_name='server',
            name='serverUrlFrp',
            field=models.URLField(null=True, verbose_name='服务器穿透址'),
        ),
        migrations.AlterField(
            model_name='server',
            name='serverUrlLan',
            field=models.URLField(verbose_name='服务器内网IPv4地址'),
        ),
        migrations.AlterField(
            model_name='server',
            name='serverUrlWan',
            field=models.URLField(null=True, verbose_name='服务器公网IPv4地址'),
        ),
        migrations.AlterField(
            model_name='server',
            name='serverUrlWan6',
            field=models.URLField(null=True, verbose_name='服务器公网IPv6地址'),
        ),
    ]
